name = "cog"
main = "src/index.ts"
compatibility_date = "2022-09-09"

account_id = "345c5ea0a3dc752d06d6fca78a96170f"

routes = [
  { pattern = "cog.scstem.tech", custom_domain = true, zone_name = "scstem.tech" }
]

minify = true

[site]
bucket = "./assets"